#!/bin/sh
# tpope's git_template/hooks/ctags, butchered beyond comprehension
set -e
ctags_opt="--tag-relative=yes"
tags_file=.git/tags
inflight_tags_file=.git/tags.under_construction.$$
new_tags_file=.git/tags.new.$$
newer_tags_file=.git/tags.newer.$$
if [ -z "$DEBUG" ]; then
    trap "rm -f $inflight_tags_file $newer_tags_file $new_tags_file" EXIT
fi

if [ -z "$1" ]; then
    test -n "$DEBUG" && echo \
    git ls-files'|'ctags $ctags_opt -L - -f$inflight_tags_file
    git ls-files | ctags $ctags_opt -L - -f$inflight_tags_file
    test -n "$DEBUG" && echo \
    mv $inflight_tags_file $tags_file
    mv $inflight_tags_file $tags_file
    exit 0
fi

whatchanged() {
    git diff --raw "$1"|awk '/^:/ {print $6}'|sort -u
}

since=$1
changed_files=$(whatchanged $since)
pipe_separated_files=$(echo $changed_files | sed -e 's/ /|/g')
test -n "$DEBUG" && echo \
grep -Ev '"	\.\./('$pipe_separated_files')	"' $tags_file '>' $inflight_tags_file
grep -Ev  "	\.\./($pipe_separated_files)	"  $tags_file  >  $inflight_tags_file

not_deleted=
for f in $changed_files; do
    if [ -f $f ]; then
	if [ -z "$not_deleted" ]; then
	    not_deleted=$f
	else
	    not_deleted="$not_deleted $f"
	fi
    fi
done

test -z "$not_deleted" && exit 0

test -n "$DEBUG" && echo \
ctags $ctags_opt --append -f$inflight_tags_file $not_deleted
ctags $ctags_opt --append -f$inflight_tags_file $not_deleted

cp $inflight_tags_file $tags_file
