#!/bin/sh
# tpope's git_template/hooks/ctags, butchered beyond comprehension
set -e
git_dir=$(git rev-parse --git-dir)
ctags_opt="--tag-relative=yes"
tags_file=${git_dir}/tags
inflight_tags_file=${git_dir}/tags.under_construction.$$
new_tags_file=${git_dir}/tags.new.$$
newer_tags_file=${git_dir}/tags.newer.$$

if [ -z "$DEBUG" ]; then
    trap "rm -f $inflight_tags_file $newer_tags_file $new_tags_file" INT QUIT EXIT
fi

cscope_xref_file=${git_dir}/cscope.out
repo_has_c_file() {
    git ls-files|awk 'BEGIN {nocfile=1} /\.c$/ { nocfile=0; exit 0; } END { exit nocfile; }'
}
generate_cscope_xref_file() {
    cscope -b -f $cscope_xref_file `git ls-files -- '*.[ch]'`
}

maybe_fixtag() {
    which fixtag >/dev/null || return
    tags_file=$1
    old=${tags_file}.old
    if [ -f ${tags_file}.need_fix ]; then
	mv $tags_file $old
	fixtag $old > $tags_file
    fi
}

run_tags_clean_if_exist() {
    if [ -x ${tags_file}.clean ]; then
	./${tags_file}.clean
    fi
}
trap run_tags_clean_if_exist 0

if [ -f ${git_dir}/nocfilehere ]; then
    # note:
    # Create ${git_dir}/nocfiles to disable possible slow check to repo_has_c_file()
    :
elif [ -f $cscope_xref_file ]; then
    generate_cscope_xref_file
elif repo_has_c_file; then
    generate_cscope_xref_file
fi

if [ -z "$1" ]; then
    test -n "$DEBUG" && echo \
    git ls-files'|'ctags $ctags_opt -L - -f$inflight_tags_file
    git ls-files | ctags $ctags_opt -L - -f$inflight_tags_file
    test -n "$DEBUG" && echo \
    mv $inflight_tags_file $tags_file
    mv $inflight_tags_file $tags_file
    maybe_fixtag $tags_file
    exit 0
fi

whatchanged() {
    git diff --raw "$1"|awk '/^:/ {print $6}'|sort -u
}

since=$1
changed_files=$(whatchanged $since)
pipe_separated_files=$(echo $changed_files | sed -e 's/ /|/g')
test -n "$DEBUG" && echo \
grep -Ev '"	\.\./('$pipe_separated_files')	"' $tags_file '>' $inflight_tags_file
grep -Ev  "	\.\./($pipe_separated_files)	"  $tags_file  >  $inflight_tags_file

not_deleted=
for f in $changed_files; do
    if [ -f $f ]; then
	if [ -z "$not_deleted" ]; then
	    not_deleted=$f
	else
	    not_deleted="$not_deleted $f"
	fi
    fi
done

test -z "$not_deleted" && exit 0

test -n "$DEBUG" && echo \
ctags $ctags_opt --append -f$inflight_tags_file $not_deleted
ctags $ctags_opt --append -f$inflight_tags_file $not_deleted

mv -f $inflight_tags_file $tags_file
maybe_fixtag $tags_file
